# Generated by Django 3.1 on 2025-05-04 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0004_auto_20250504_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('thumbnail', models.ImageField(upload_to='photos/news/thumbnail')),
                ('images', models.ImageField(upload_to='photos/news/')),
                ('short_description', models.TextField(blank=True, max_length=500)),
                ('long_description', models.TextField(blank=True)),
                ('meta_title', models.TextField(blank=True, max_length=500)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keyword', models.TextField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('is_discussed', models.BooleanField(default=False)),
                ('is_selected', models.BooleanField(default=False)),
                ('is_image', models.BooleanField(default=False)),
                ('is_top', models.BooleanField(default=False)),
                ('is_publish', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
