# Generated by Django 3.1 on 2025-05-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20250503_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='section_no',
            field=models.IntegerField(null=True),
        ),
    ]
