# Generated by Django 3.1 on 2025-05-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20250504_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='section_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
